run:
	deno run --allow-read --allow-net --unstable --import-map=import_map.json https://raw.githubusercontent.com/imaginamundo/jsx-framework/v0.0.2/mod.js

reload:
	deno cache --reload --unstable https://raw.githubusercontent.com/imaginamundo/jsx-framework/v0.0.2/mod.js